apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:2bfcd47f4e045d4ac6d579704eafc29ee155247736d78286417b9fb69eabe067
  # name: quay.io/siamaksade/spring-petclinic:latest
  name: demo-registry-quay-quay-demo.apps.ocp4hub.sandbox963.opentlc.com/cicd-demo/food-app:latest
  # newName: image-registry.openshift-image-registry.svc:5000/pac-demo-pipelines/spring-petclinic
  newName: demo-registry-quay-quay-demo.apps.ocp4hub.sandbox963.opentlc.com/cicd-demo/food-app
